ctransformers:
  model_path:
    small: "./models/mistral_7b_instruct_v0.1.Q3_K_M.gguf"
    large: "./models/mistral_7b_instruct_v0.1.Q5_K_M.gguf"
   
  
  model_type: "mistral"

  model_config:
    'max_new_tokens': 512
    'temperature': 0.3
    'context_length': 4096 
    'gpu_layers': 0 
    'threads': '-1'

chat_config:
  chat_memory_length: 2
  number_of_retrieved_documents: 3

pdf_text_splitter:
  chunk_size: 1024
  overlap: 50
  seperators: ["\n\n", "\n"]

llava_model:
  llava_model_path: "./models/llava/ggml-model-q5_k.gguf"
  clip_model_path: "./models/llava/mmproj-model-f16.gguf"

wishper_model: "openai/whisper-small"

embeddings_path:  "BAAI/bge-large-en-v1.5"

chromadb:
  chromadb_path: "chromadb"
  collections_name: "pdfs" 

chat_history_path: "./chat_sessions"

chat_sessions_database_path: "./chat_sessions/chat_sessions.db"
